### ISSUE TITLE
needs admin work

### ISSUE THREAD

**Issue by jspaaks** [NicoRenaud/Spot_tutorial_easy-#4]
looks like somthign's off with the synching between github and gitbook. Am I correct in saying that we have two git repo's ([github](https://github.com/NicoRenaud/Spot_tutorial_easy-.git), [gitbook](https://git.gitbook.com/nicorenaud/spot-first-step.git)) with the same content? If so, it's probably better to reduce to one (the one on github I'd say) to avoid maintenance nightmares. 

Also, the content of the remaining repo should probably be moved to under github.com/NLeSC somewhere.

And maybe merged into SPOT's repo https://github.com/NLeSC/spot. I'll look into that.
update: something like this https://stackoverflow.com/questions/1683531/how-to-import-existing-git-repository-into-another#answer-1684694

**Comment by NicoRenaud** [comment]
We should see if Faruk and Jyisk want the tutorial diectly in SPOT 
That would make sense but they're the boss.
I'll email them and keep you posted

**Comment by jspaaks** [comment]
OK, I tested the approach and know how to merge this repo into NLeSC/spot without losing commit history.

**Comment by jspaaks** [comment]
So after some discussion, @fdiblen decided to put the tutorial files into their own repo, but under the NLeSC organization. I've been updating the repo that Faruk created here (https://github.com/NLeSC/spot-tutorial). That should be the only SPOT tutorial repo from this point forward IMHO.
